
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - c2
      - c3
  

  c3:
    build:
      context: ./c3
    ports:
      - "8000:8000"

  c2:
    build:
      context: ./c2
    ports:
      - "8001:8001"